# When pushing a tag. this workflow will trigger site deployment and fixed version address comments

name: Deploy website
on:
  push:
    tags:
      - '5.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: (startsWith(github.ref, 'refs/tags/') && (contains(github.ref_name, '-') == false)) || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - name: build site
        run: bun run predeploy
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: build dist and bundle analyzer report
        run: bun run dist
        env:
          ANALYZER: 1
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Get version
        id: publish-version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/\./-/g')" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "antd-kr"
          git config --global user.email "antd-kr@example.com"

          mkdir deploy
          cd deploy
          git init
          git remote add origin git@github.com:ant-design-korea/ant-design-korea.github.io.git
          git fetch origin
          git checkout -b gh-pages
          cp -r ../_site/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
    timeout-minutes: 30
